image: node:8.15.0
stages:
  - build
  - test
cache:
      paths:
        - node_modules/
install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/
testing:
      stage: test
      script:
        - npm run lint