// GITHUB USER
export const RECEIVE_GITHUB_USER = 'RECEIVE_GITHUB_USER'
export const RESET_LIST_GITHUB_USER = 'RESET_LIST_GITHUB_USER'
export const UPDATE_STATE_GITHUB_USER = 'UPDATE_STATE_GITHUB_USER'
export const FAILED_GITHUB_USER = 'FAILED_GITHUB_USER'
